<a href="https://colab.research.google.com/github/malickl/Pratique_Arbre-de-Decision/blob/main/Arbre_de_decision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importer les librairies
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris

In [ ]:
import random
random.seed(0)

In [ ]:
#Charger le dataset Iris
iris = load_iris()
X,y = iris.data, iris.target

In [ ]:
# Combien y a-t-il d'examples de chaque classe
np.bincount(iris.target)

array([50, 50, 50])

In [ ]:
# Creation du jeu d’apprentissage et de test
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [ ]:
# Construire un arbre de décision
modelTree = tree.DecisionTreeClassifier(random_state=0)
modelTree.fit(X_train, y_train)

DecisionTreeClassifier(random_state=0)

In [ ]:
#Calculer le taux de performance du modèle
accuracyTreeTest = modelTree.score(X_test, y_test)
print("Accuracy Abre x_test : ", accuracyTreeTest)

Accuracy Abre x_test :  1.0


In [ ]:
# Tester les paramètres max_deppth et min_samples_split
# Le paramètre max_depth est un seuil de profondeur maximal de l'arbre
# Le paramètre min_samples leaf donne le nombre miimal d’échantillons danns un noeud de feuille
# Il permettent de mettre des contraintes sur la construction de l'arbre
# et donc de controler indirectement le phénomène de sur-apprentissage

for mdepth in [1,2,3,4,10]:
  clf = tree.DecisionTreeClassifier(max_depth=mdepth)
  clf = clf.fit (X_train, y_train)
  print(clf.score(X_test, y_test))

print('')

for msplit in [2, 3, 5, 10, 20]:
  clf = tree.DecisionTreeClassifier(min_samples_split=msplit)
  clf = clf.fit(X_train, y_train)
  print(clf.score(X_test, y_test))

0.6333333333333333
0.9666666666666667
1.0
1.0
1.0

1.0
1.0
1.0
1.0
1.0


In [ ]:
modelTree = tree.DecisionTreeClassifier( max_depth=4, min_samples_split=2, random_state=0)
modelTree.fit(X_train, y_train)
accuracyTreeTest = modelTree.score(X_test, y_test)
print("Accuracy Abre x_test : ", accuracyTreeTest)

Accuracy Abre x_test :  1.0


In [ ]:
#Prediction test
modelTree.predict([[5.5,3.5,1.5,0.25]])

array([0])

In [ ]:
modelTree.predict([[6.0, 2.8,4.3,1.3]])

array([1])